spring:
  datasource:
    url: jdbc:mysql://115.29.161.170:3306/mock
    username: destiny
    password: mICROPOPLAR@2016
    driverClassName: com.mysql.jdbc.Driver
    
    dbcp:
      max-active: 8
      initial-size: 5
      max-idle: 5
      min-idle: 1
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 5000
      min-evictable-idle-time-millis: 6000

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

  data:
    rest:
      base-path: /rest
      default-page-size: 10

  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb

server:
  port: 9310

#myProps:
#  qiniu:
#    accessKey: f-4qhQ_bGUQVhEryo-XUF89Njqeg1SgDJ2uKVv3Y
#    secretKey: 9O1xieJDu76UxsRPkt9g-v-oMbh9wgrC5dpIwPKd
#    BUCKET: mp
#    DOMAIN: http://ogw9ek3ff.bkt.clouddn.com
